- name: first play
  become: yes
  hosts: localhost
  tasks:
    - name: key value pair1
      ansible.builtin.debug:
      msg: "mentioned one is: {{item}}"
      loop:
        - kiran
        - kumar
        - uppu
      